# Generated by Django 4.1 on 2023-01-20 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0003_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station', to='user_account.station'),
        ),
    ]
