# Generated by Django 4.1 on 2023-01-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0004_alter_user_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='district',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
