# Generated by Django 4.1 on 2022-08-09 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind_speed', models.FloatField(null=True)),
                ('wind_direction', models.PositiveIntegerField()),
                ('max_temperature', models.FloatField(null=True)),
                ('min_temperature', models.FloatField(null=True)),
                ('dry_bulb', models.FloatField(null=True)),
                ('wet_bulb', models.FloatField(null=True)),
                ('dew_point', models.CharField(max_length=100, null=True)),
                ('pressure_value', models.FloatField(null=True)),
                ('isobaric_value', models.PositiveIntegerField(null=True)),
                ('ground_max_temp', models.FloatField(null=True)),
                ('low_clouds', models.CharField(max_length=350)),
                ('middle_clouds', models.CharField(max_length=350)),
                ('high_clouds', models.CharField(max_length=350)),
                ('sunshine', models.FloatField(null=True)),
                ('evaporation', models.FloatField(null=True)),
                ('relative_humidity', models.PositiveIntegerField(null=True)),
                ('rainfall_amount', models.CharField(max_length=100, null=True)),
                ('total_Cloud_amount', models.PositiveIntegerField()),
                ('present_weather', models.CharField(max_length=10, null=True)),
                ('past_weather', models.CharField(max_length=10, null=True)),
                ('pastTwentyWeather', models.CharField(max_length=10, null=True)),
                ('lowcloud_amount', models.CharField(max_length=10, null=True)),
                ('middlecloud_amount', models.CharField(max_length=10, null=True)),
                ('highcloud_amount', models.CharField(max_length=10, null=True)),
                ('lowcloud_height', models.CharField(max_length=10, null=True)),
                ('middlecloud_height', models.CharField(max_length=10, null=True)),
                ('highcloud_height', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_info', to='user_account.station')),
            ],
        ),
    ]
