# Generated by Django 4.1 on 2022-12-23 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0003_alter_synop_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['-created_at']},
        ),
    ]
