# Generated by Django 4.1 on 2022-12-23 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0004_alter_data_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='synop',
            options={'ordering': ['-created']},
        ),
    ]
