# Generated by Django 4.1.7 on 2023-04-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0005_alter_synop_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='total_Cloud_amount',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
