# Generated by Django 4.1.7 on 2023-04-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0006_alter_data_total_cloud_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='isobaric_value',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
