# Generated by Django 4.1.7 on 2023-04-28 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_station_created_station_updated'),
        ('codes', '0007_alter_data_isobaric_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='station_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_info', to='user_account.station'),
        ),
    ]
