# Generated by Django 4.1.7 on 2023-04-28 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_station_created_station_updated'),
        ('codes', '0008_alter_data_station_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='synop',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_account.station'),
        ),
    ]
